name: wealth_app
description: "A Flutter eCommerce app with Supabase backend integration"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.13+13

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.8.0
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  go_router: ^12.0.0
  flutter_hooks: ^0.20.0
  flutter_animate: ^4.2.0
  shimmer: ^3.0.0
  responsive_framework: ^1.1.0
  flutter_screenutil: ^5.9.0
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0
  permission_handler: ^11.0.0
  connectivity_plus: ^5.0.0
  package_info_plus: ^8.0.0
  freezed_annotation: ^2.4.1
  path: ^1.8.3
  share_plus: ^7.2.2
  json_annotation: ^4.9.0
  app_links: ^6.3.2
  intl: ^0.17.0
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.0
  flutter_paystack_max: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.0
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/core/services/database/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
